### ISSUE TITLE
Modifying the Botania Lexicon doesn't work

### ISSUE THREAD

**Issue by DiamondCookie** [joshiejack/ModTweaker#84]
I tried to add/remove to/from the botania lexicon, though, it doesn't work.
Here is the error inside the log:
ERROR: botania.zs:14 > No such member: Lexicon
ERROR: Error executing botania.zs: 4
java.lang.ArrayIndexOutOfBoundsException: 4
	at stanhebben.zenscript.type.natives.JavaMethod.rematch(JavaMethod.java:152)
	at stanhebben.zenscript.expression.ExpressionCallVirtual.<init>(ExpressionCallVirtual.java:37)
	at stanhebben.zenscript.type.ZenTypeAny.call(ZenTypeAny.java:201)
	at stanhebben.zenscript.expression.Expression.call(Expression.java:81)
	at stanhebben.zenscript.parser.expression.ParsedExpressionCall.compile(ParsedExpressionCall.java:42)
	at stanhebben.zenscript.statements.StatementExpression.compile(StatementExpression.java:19)
	at stanhebben.zenscript.ZenModule.compileScripts(ZenModule.java:124)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:153)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:82)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610)
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by jaredlll08** [comment]
That would be because this version doesn't support that...

**Comment by DiamondCookie** [comment]
Doesn't support version of what? Modtweaker? Botania? and which version is supported?

**Comment by jaredlll08** [comment]
As far as I know, @soundlogic2236 added Lexica Botania editing in ModTweaker2, this is modtweaker, and ModTweaker2 is not released yet... I dont know what versions you have...

**Comment by DiamondCookie** [comment]
My Botania version is r1.5-162 and Modtweaker version is 0.6-0. Lexicon Modification was in the wiki, so I thought the fact that it wasn't working was probably a bug. Do we have a release date of Modtweaker 2?

**Comment by Yulife** [comment]
It is not for the public. Jared said earlier that it is in Modtweaker2 and you are infact on Modtweaker1.
